### ISSUE TITLE
can not set data

### ISSUE THREAD

**Issue by SecretKeeper** [rubystarashe/nuxt-vuex-localstorage#1]
hello , first thanks for publishing this awesome plugin
i have an issue with using it

1.i try like this , in `nuxt.config.js`

`    
    modules: [
        'nuxt-vuex-localstorage'
    ]
`

2. Created `localStorage.js` in `store` folder
`
export const state = () => ({
    my_custom_value: 33
})
`
3. and in view page i use this
`<div>{{ $store.state.localStorage }}</div>
`

and the results is:

`{ status: true } // there is no my_custom_value` 

i have also tried with `computed load()` function but same result

also this is my `store/index.js`:

`
import Vuex from 'vuex';
    const createStore = () => {
        return new Vuex.Store({
        state: () => ({
            counter: 0
        }),
        mutations: {
            increase (state) {
                state.counter++
            }
        }
    })
}
export default createStore
`

**Comment by rubystarashe** [comment]
check this example
https://github.com/rubystarashe/nuxt-vuex-localstorage-example
it works fine

**Comment by SecretKeeper** [comment]
thank you , works very well 
would you develop this plugin for future?

**Comment by rubystarashe** [comment]
Of course.
There have been a lot of updates this time, so I hope you will take note of them.
