### ISSUE TITLE
How to use Cookies instead of localStorage?

### ISSUE THREAD

**Issue by razukc** [rubystarashe/nuxt-vuex-localstorage#12]
My config:
`['nuxt-vuex-localstorage', {
			localStorage: ['socket', 'support']
		   }]`

I want to use cookies instead. How do I achieve that?

**Comment by rubystarashe** [comment]
`module.exports = {
  modules: [
    ['nuxt-vuex-localstorage', {
      mode: 'cookie',
      expireHours: 24
    }]
  ]
}`

ive updated cookie only mode.
