### ISSUE TITLE
Use localStorage in existing module

### ISSUE THREAD

**Issue by simplenotezy** [rubystarashe/nuxt-vuex-localstorage#20]
I have a module called "cart.js". How can I enable storage for this module? Do I really have to contain states inside the "localStorage.js" file, or can I somehow just tell the module to save keys in localStorage?

**Comment by who-is-apo** [comment]
<img width="224" alt="Screenshot 2020-06-18 at 16 38 47" src="https://user-images.githubusercontent.com/1695865/85034262-3158f600-b182-11ea-8806-bf6ce90c80d7.png">
Just modify the config

**Comment by simplenotezy** [comment]
Thanks for your reply! Will that store EVERY key in localstorage for the given store?

**Comment by rubystarashe** [comment]
yes
