### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by afoncatti** [rubystarashe/nuxt-vuex-localstorage#21]
This error happens when the nuxt app is opened through a webview in the native script version of the app. Any hints of what is going on?

It happens on this the get method in the following line:
`const localPersist = JSON.parse(crypto.decrypt(storageFunction.local.get(name)))`

![image](https://user-images.githubusercontent.com/51166901/87045792-ad1cf000-c1ce-11ea-9132-61759a740057.png)

**Comment by rubystarashe** [comment]
The environment does not seem to support localStorage and cookie.

Or there may be separate methods for accessing localStorage. If your environment supports localStorage, please let me know the specific method.

**Comment by rubystarashe** [comment]
this issue is fixed
