### ISSUE TITLE
When used under ie11, the login status cannot be stored, and the status will disappear after the page is refreshed,

### ISSUE THREAD

**Issue by wzs28150** [rubystarashe/nuxt-vuex-localstorage#25]
Version 1.2.7

My project is to save and keep the login status when I log in. I found that when I use it under ie11, I can't save the login status. After refreshing the page, the status will disappear.

I set up transpile and it still doesn't work. What should I do?

**Comment by SSebigo** [comment]
@wzs28150  Any news about this issue?

**Comment by rubystarashe** [comment]
It's working with IE(not edge)

please check this example. https://github.com/rubystarashe/nuxt-vuex-localstorage-example
