### ISSUE TITLE
Axios high severity vulnerability

### ISSUE THREAD

**Issue by justinwride** [rubystarashe/nuxt-vuex-localstorage#26]
The current version of the "axios" dependency is "^0.19.2".
This version contains a **high severity** vulnerability for Server-Side Request Forgery (SSRF).

The vulnerability is fixed in version "0.21.1" or later.

See https://npmjs.com/advisories/1594

**Comment by sdailly** [comment]
Any news about this issue ?

**Comment by justinwride** [comment]
Opened PR to address the issue. https://github.com/rubystarashe/nuxt-vuex-localstorage/pull/30

**Comment by davidFagerburg** [comment]
Can we get this merged in? It would be really great @rubystarashe

**Comment by code-leen** [comment]
Would highly appreciate this getting merged in! @rubystarashe pls and thank u

**Comment by rubystarashe** [comment]
@justinwride @davidFagerburg @colleenkingcode Thank you and sorry for late... I've been busy.
