### ISSUE TITLE
Got error "Uncaught SyntaxError: Unexpected token ..."

### ISSUE THREAD

**Issue by attract** [rubystarashe/nuxt-vuex-localstorage#3]
Version:
"nuxt": "^2.0.0"
"nuxt-vuex-localstorage": "^1.2.6"

```
 const bindLocalStorage = name => {
    const localPersist = JSON.parse(crypto.decrypt(storageFunction.local.get(name)))
    let data = { ...store.state }
    const expireChecked = nuxt_vuex_localstorage_plugins_bindStorage_expire__WEBPACK_IMPORTED_MODULE_1__["default"].check(localPersist)
    if (store.state[name] && expireChecked[versionPropName] === store.state[name][versionPropName])
      data[name] = { ...data[name], ...expireChecked, status: true }
    store.replaceState(data)

    localStoreNames.forEach((name, i) => {
      watchHandlers_local[i] = watcher_local(name, i)
    })
  }

```

Error in line `let data = { ...store.state }`

Can you help?

Thanks

**Comment by attract** [comment]
I tried to update the version `nuxt` to `2.4.3` (as in the example - https://github.com/rubystarashe/nuxt-vuex-localstorage-example), the error remained..

**Comment by rubystarashe** [comment]
Check your nuxt.config.js. Perhaps that syntax error can occur if a module is loaded from the wrong position(such as before nuxt compile)

https://github.com/rubystarashe/nuxt-vuex-localstorage-example
Is it not working? I tested this repo a little while ago, and it works.

**Comment by attract** [comment]
I did not check your example, only compare package version with my `package.json`

Trying change position in `package.json`, set the last, same result.

**Comment by stasoft91** [comment]
IE11, I guess it is some babel-kind error, no object spread in older browsers, but i can find object spread in vendors.app.js

**Comment by Untaek** [comment]
Hi. I solved this issue. How it works
```javascript
// Add that code to nuxt.config.js
build: {
  // ...
  transpile: [
    /(.+)(nuxt-vuex-localstorage\/)(.+)(\.js)$/
  ],
  // ...
}
```

This build option make to transpile specific library.
And when you try to run any build script, incompatible codes will be changed.

**Comment by akeyboardlife** [comment]
> Hi. I solved this issue. How it works
> 
> ```js
> // Add that code to nuxt.config.js
> build: {
>   // ...
>   transpile: [
>     /(.+)(nuxt-vuex-localstorage\/)(.+)(\.js)$/
>   ],
>   // ...
> }
> ```
> 
> This build option make to transpile specific library.
> And when you try to run any build script, incompatible codes will be changed.

It's wierd why 
```
build: {
  // ...
  transpile: [
    "nuxt-vuex-localstorage"
  ],
  // ...
}
```
won't work.

As stated [here](https://nuxtjs.org/api/configuration-build/#transpile), it can be a package name.

**Comment by rubystarashe** [comment]
maybe it was problem specific version nuxt
