### ISSUE TITLE
IE11 not opening website

### ISSUE THREAD

**Issue by maziarz** [rubystarashe/nuxt-vuex-localstorage#7]
I recently noticed that ie11 is not opening my website.

> SCRIPT1028: SCRIPT1028: Expected identifier, string or number

Unfortunately i had to debug this in browserstack and it refers to the line: `let data = { ...store.state }`

Is this a lack of polyfill for IE11?

<img width="1081" alt="Skærmbillede 2019-03-19 kl  00 00 39" src="https://user-images.githubusercontent.com/15786116/54569158-12e1d900-49da-11e9-84a8-0b2581ef66be.png">

**Comment by rubystarashe** [comment]
try use the transpile options in nuxt.config.js

**Comment by maziarz** [comment]
Should `@babel/polyfill` do the trick?

**Comment by maziarz** [comment]
When i do that, this is what happens in Chrome

```
commons.app.js:11814 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (commons.app.js:11814)
    at Module../node_modules/nuxt-vuex-localstorage/node_modules/axios/lib/utils.js (commons.app.js:11836)
    at __webpack_require__ (runtime.js:787)
    at fn (runtime.js:150)
    at Module.<anonymous> (commons.app.js:10321)
    at Module../node_modules/nuxt-vuex-localstorage/node_modules/axios/lib/axios.js (commons.app.js:10368)
    at __webpack_require__ (runtime.js:787)
    at fn (runtime.js:150)
    at Object../node_modules/nuxt-vuex-localstorage/node_modules/axios/index.js (commons.app.js:10104)
    at __webpack_require__ (runtime.js:787)
```

**Comment by rubystarashe** [comment]
![캡처](https://user-images.githubusercontent.com/24281584/54840477-805e7400-4d10-11e9-857a-5507bd276e08.PNG)

Try nuxt-vuex-localstorage-example repo. it works well

**Comment by maziarz** [comment]
I double checked with your example. The only difference is that i am using `nuxt 2.5.1`. Otherwise it looks the same.

**Comment by maziarz** [comment]
Seems to be a node_modules problem, i cleared the folder and deleted the `package-lock.json`, now it seems to be working!

**Comment by seanaye** [comment]
I cleared package-lock.json and node_modules. I and getting Cannot assign to read only property 'exports' of object '#<Object>' in chrome

Nuxt 2.9.1

**Comment by bpeab** [comment]
Also having `Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'` when `nuxt-vuex-localstorage` is added to the `transpile` array. Not adding it, breaks IE 11 anyway.

**Comment by seanaye** [comment]
@bpeab try adding

    build: {
        sourceType: ‘unambiguous’
        ...
    }

It worked for me
