### ISSUE TITLE
How to use localstorage for 'index' module (default)

### ISSUE THREAD

**Issue by pun-ky** [rubystarashe/nuxt-vuex-localstorage#8]
In few places in my app I am using default store (not namespaced) and I also want to have it synced with local storage.

![image](https://user-images.githubusercontent.com/10673561/58387564-b837af80-8010-11e9-95bd-07079695a498.png)

Is it possible to set somehow localstorage working also for store/index.js values without moving it into named module (non-index) ?

While using 'index' it is not working... :/

**Comment by rubystarashe** [comment]
Check this.
```js
//  nuxt.config.js
module.exports = {
  modules: [
    ['nuxt-vuex-localstorage', {
      localStorage: ['foo', 'bar'],  //  If not entered, “localStorage” is the default value
      sessionStorage: ['sfoo', 'sbar']  //  If not entered, “sessionStorage” is the default value
    }]
  ]
}

// store/index.js
export const state = () => ({
  foo: {
    anyValues: 0
  },
  bar: {
    anyValues: 0
  },
  sfoo: {
    anyValues: 0
  },
  sbar: {
    anyValues: 0
  }
})
```

Use ['foo', 'bar', 'tumbleRabbit', 'sweet', 'dino'] instead of ['index', 'tumbleRabbit', 'sweet', 'dino']

This module would observe all items of store with deep options.
store/tumbleRabbit.js in nuxt store module usage is the same as this of store/index.js
```js
// store/index.js
export const state = () => ({
  tumbleRabbit: value
})
```

**Comment by Albertbol** [comment]
Please add it to read me, very useful information ;)

**Comment by pun-ky** [comment]
Fine thank you
