### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by auedbaki** [rubystarashe/nuxt-vuex-localstorage#9]
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (commons.app.js:7813)
    at Module../node_modules/nuxt-vuex-localstorage/node_modules/axios/lib/utils.js (commons.app.js:7835)
    at __webpack_require__ (runtime.js:796)
    at fn (runtime.js:151)
    at Module.<anonymous> (commons.app.js:6371)
    at Module../node_modules/nuxt-vuex-localstorage/node_modules/axios/lib/axios.js (commons.app.js:6418)
    at __webpack_require__ (runtime.js:796)
    at fn (runtime.js:151)
    at Object../node_modules/nuxt-vuex-localstorage/node_modules/axios/index.js (commons.app.js:6172)
    at __webpack_require__ (runtime.js:796)

**Comment by seanaye** [comment]
I am also getting this error when I include the ie transpile. 
build: {
    /*
    ** You can extend webpack config here
    */
    transpile: [
      'nuxt-vuex-localstorage'
    ],
    extend(config, ctx) {
      
    }
  }

I need to have ie compatibility

**Comment by drewbaker** [comment]
I'm getting a `TypeError: "exports" is read-only` error with this too. Nuxt version `2.9.2` when I had `transpile: ["vuex"],` in my nuxt.config.js `build` function.

![Screen Shot 2019-09-13 at 7 08 12 PM](https://user-images.githubusercontent.com/475015/64902309-ebeb2380-d659-11e9-96d9-0ac5554f6240.png)

**Comment by RowEchelonForm** [comment]
I was struggling with the same issue when using the ie transpile. In my case, I was able to fix it by adding `sourceType: 'unambiguous'` under babel property under build in nuxt.js.config. Like this:

```
  build: {
    babel: {
      sourceType: 'unambiguous',
    },
    transpile: [
      'nuxt-vuex-localstorage',
    ],
  }
```

This could cause some other unforeseen issues and I don't really know what it does beyond what it says in Babel documentation: https://babeljs.io/docs/en/options#sourcetype. I'd like to know if there is a better way to fix this, but this seems to work for me.

**Comment by nelsonlarocca** [comment]
thanks for sharing that fix @RowEchelonForm 
any advance about that ?
I just started getting that problem recently. Currently using Nuxt 2.11

**Comment by rubystarashe** [comment]
old version nuxt's issue
This seems to be solved.
